### ISSUE TITLE
Build fails: error: no member named 'lp_' in 'Highs'

### ISSUE THREAD

**Issue by yurivict** [ERGO-Code/HiGHS#675]
```
In file included from /disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/Highs.h:21:
In file included from /disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/lp_data/HighsLpUtils.h:23:
In file included from /disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/lp_data/HighsLp.h:22:
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/lp_data/HStruct.h:30:1: warning: 'HighsSolution' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct HighsSolution {
^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.hpp:24:1: note: did you mean struct here?
class HighsSolution;
^~~~~
struct
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:340:23: error: no member named 'lp_' in 'Highs'
  return this->highs->lp_.num_col_;
         ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:347:23: error: no member named 'lp_' in 'Highs'
  return this->highs->lp_.num_row_;
         ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:354:23: error: no member named 'lp_' in 'Highs'
  return this->highs->lp_.a_matrix_.start_[this->highs->lp_.num_col_];
         ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:354:57: error: no member named 'lp_' in 'Highs'
  return this->highs->lp_.a_matrix_.start_[this->highs->lp_.num_col_];
                                           ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:361:25: error: no member named 'lp_' in 'Highs'
  return &(this->highs->lp_.col_lower_[0]);
           ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:368:25: error: no member named 'lp_' in 'Highs'
  return &(this->highs->lp_.col_upper_[0]);
           ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:375:25: error: no member named 'lp_' in 'Highs'
  return &(this->highs->lp_.row_lower_[0]);
           ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:382:25: error: no member named 'lp_' in 'Highs'
  return &(this->highs->lp_.row_upper_[0]);
           ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:389:25: error: no member named 'lp_' in 'Highs'
  return &(this->highs->lp_.col_cost_[0]);
           ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:418:30: error: no member named 'lp_' in 'Highs'
    double lo = this->highs->lp_.row_lower_[i];
                ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:419:30: error: no member named 'lp_' in 'Highs'
    double hi = this->highs->lp_.row_upper_[i];
                ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:446:30: error: no member named 'lp_' in 'Highs'
    double lo = this->highs->lp_.row_lower_[i];
                ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:447:30: error: no member named 'lp_' in 'Highs'
    double hi = this->highs->lp_.row_upper_[i];
                ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:474:30: error: no member named 'lp_' in 'Highs'
    double lo = this->highs->lp_.row_lower_[i];
                ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:475:30: error: no member named 'lp_' in 'Highs'
    double hi = this->highs->lp_.row_upper_[i];
                ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:501:32: error: no member named 'lp_' in 'Highs'
  memcpy(start, &(this->highs->lp_.a_matrix_.start_[0]),
                  ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:503:32: error: no member named 'lp_' in 'Highs'
  memcpy(index, &(this->highs->lp_.a_matrix_.index_[0]),
                  ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:505:32: error: no member named 'lp_' in 'Highs'
  memcpy(value, &(this->highs->lp_.a_matrix_.value_[0]),
                  ~~~~~~~~~~~  ^
/disk-samsung/freebsd-ports/math/highs/work/HiGHS-vv1.1.1-886-g697c7a88/src/interfaces/OsiHiGHSSolverInterface.cpp:539:31: error: no member named 'lp_' in 'Highs'
  return (double)this->highs->lp_.sense_;
                 ~~~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

clang-12
FreeBSD 13

**Comment by felixlen** [comment]
This has been reported in #580 and fixed by #592, however the pull request has been reverted back then. I think the reason for reverting the pull request has been fixed, so that the fix of #592 should be able to be applied by now?

**Comment by jajhall** [comment]
The OSI interface has been broken for a while. I tried to fix it in the summer, but there are some software engineering issues to sort out, and this has to wait until the Integration and Development Manager takes up their post in March, sorry.

**Comment by yurivict** [comment]
@jajhall 
So the 1.1.1 release is broken?

**Comment by jajhall** [comment]
V1.1.1, as tagged on 27 September 2021, hasn't changed. Anything since then is a development version. What GitHash after that works for you? The fix proposed by @felixlen in #592 (after 27/09) had to be rejected, and HiGHS has moved on since then due to OpenMP being removed entirely. There may be a fix to the current master so that there is an option to disable the OSI interface, but it's not something that I can make. The person who works on the HiGHS build is not available until March, and because of this, I'm very wary of approving any "fix" to the build system.

**Comment by yurivict** [comment]
I think I tried 1.1.1 and it had the same problem, but I might be wrong.

Now I have already updated the FreeBSD port: https://cgit.freebsd.org/ports/tree/math/highs/Makefile

Since OSI is an optional dependency there should probably be a cmake variable that disables/enables it cleanly.

**Comment by jajhall** [comment]
Thanks, you may well be correct that there is a cmake variable that disables/enables OSI cleanly. I suggest that you make the modification locally.

**Comment by jajhall** [comment]
#704  should mean that OsiInterface now builds. The OSI interface still needs updating since some of the unit tests fail. This is covered by #525
