### ISSUE TITLE
BUG: Windows build regressions

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#483]
IPX is currently throwing the following error (see [logs](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=10798&view=logs&jobId=0c790cac-d60e-5695-2cee-2e3f569cb85a&j=0c790cac-d60e-5695-2cee-2e3f569cb85a&t=3337ac87-8da2-5fc3-12b4-7ce358a5e1cb)):
```
 scipy\optimize\_highs\src\ipm\ipx\src\guess_basis.cc(130): error C2039: 'max': is not a member of 'std'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\chrono(19): note: see declaration of 'std'
  scipy\optimize\_highs\src\ipm\ipx\src\guess_basis.cc(130): error C3861: 'max': identifier not found
```

Most likely a regression due to #439
