### ISSUE TITLE
TestMain.cpp fails to compile with clang 13.0.1

### ISSUE THREAD

**Issue by tosttost** [ERGO-Code/HiGHS#756]
```
/some/path/HiGHS/extern/catch.hpp:10822:34: error: constexpr variable 'sigStackSize' must be initialized by a constant expression
    static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
                                 ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/some/path/HiGHS/extern/catch.hpp:10822:58: note: non-constexpr function 'sysconf' cannot be used in a constant expression
    static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
                                                         ^
/usr/include/bits/sigstksz.h:32:22: note: expanded from macro 'MINSIGSTKSZ'
# define MINSIGSTKSZ SIGSTKSZ
                     ^
/usr/include/bits/sigstksz.h:28:19: note: expanded from macro 'SIGSTKSZ'
# define SIGSTKSZ sysconf (_SC_SIGSTKSZ)
                  ^
/usr/include/unistd.h:640:17: note: declared here
extern long int sysconf (int __name) __THROW;
                ^
In file included from /some/path/HiGHS/check/TestMain.cpp:6:
/some/path/HiGHS/extern/catch.hpp:10881:33: error: variable length array declaration not allowed at file scope
    char FatalConditionHandler::altStackMem[sigStackSize] = {};
```
This is the clang version currently used by Arch Linux.
Possibly related to https://github.com/catchorg/Catch2/issues/2178  - if so updating catch.hpp should solve the issue.

Obvious workaround: 
```
cmake path/to/highs -DBUILD_TESTING=off 
```
when building HiGHS.
